# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CONFIGURACOES.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets

import loginWindow


class Ui_config(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(850, 440)
        Form.setMinimumSize(QtCore.QSize(850, 440))
        Form.setMaximumSize(QtCore.QSize(850, 440))
        self.Usuario = QtWidgets.QLineEdit(Form)
        self.Usuario.setGeometry(QtCore.QRect(450, 90, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Usuario.setFont(font)
        self.Usuario.setStyleSheet("QLineEdit {\n"
                                   "    border: 3px solid rgb(245, 222, 179);\n"
                                   "    border-radius: 10px;\n"
                                   "    padding: 15px;\n"
                                   "    background-color:rgb(249, 234, 195);\n"
                                   "    color: rgb(45, 45, 45);\n"
                                   "}\n"
                                   "QLineEdit:hover {\n"
                                   "    border: 3px solid rgb(55, 55, 55);\n"
                                   "}\n"
                                   "QLineEdit:focus {\n"
                                   "    border: 3px solid rgb(135, 206, 250);\n"
                                   "    color: rgb(45, 45, 45);\n"
                                   "}")
        self.Usuario.setText("")
        self.Usuario.setAlignment(QtCore.Qt.AlignCenter)
        self.Usuario.setObjectName("Usuario")
        self.senha_user = QtWidgets.QLineEdit(Form)
        self.senha_user.setGeometry(QtCore.QRect(450, 150, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.senha_user.setFont(font)
        self.senha_user.setStyleSheet("QLineEdit {\n"
                                      "    border: 3px solid rgb(245, 222, 179);\n"
                                      "    border-radius: 10px;\n"
                                      "    padding: 15px;\n"
                                      "    background-color:rgb(249, 234, 195);\n"
                                      "    color: rgb(45, 45, 45);\n"
                                      "}\n"
                                      "QLineEdit:hover {\n"
                                      "    border: 3px solid rgb(55, 55, 55);\n"
                                      "}\n"
                                      "QLineEdit:focus {\n"
                                      "    border: 3px solid rgb(135, 206, 250);\n"
                                      "    color: rgb(45, 45, 45);\n"
                                      "}")
        self.senha_user.setText("")
        self.senha_user.setAlignment(QtCore.Qt.AlignCenter)
        self.senha_user.setObjectName("senha_user")
        self.Tipo = QtWidgets.QLineEdit(Form)
        self.Tipo.setGeometry(QtCore.QRect(450, 210, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Tipo.setFont(font)
        self.Tipo.setStyleSheet("QLineEdit {\n"
                                "    border: 3px solid rgb(245, 222, 179);\n"
                                "    border-radius: 10px;\n"
                                "    padding: 15px;\n"
                                "    background-color:rgb(249, 234, 195);\n"
                                "    color: rgb(45, 45, 45);\n"
                                "}\n"
                                "QLineEdit:hover {\n"
                                "    border: 3px solid rgb(55, 55, 55);\n"
                                "}\n"
                                "QLineEdit:focus {\n"
                                "    border: 3px solid rgb(135, 206, 250);\n"
                                "    color: rgb(45, 45, 45);\n"
                                "}")
        self.Tipo.setText("")
        self.Tipo.setAlignment(QtCore.Qt.AlignCenter)
        self.Tipo.setObjectName("Tipo")
        self.Senha_antiga = QtWidgets.QLineEdit(Form)
        self.Senha_antiga.setGeometry(QtCore.QRect(180, 90, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Senha_antiga.setFont(font)
        self.Senha_antiga.setStyleSheet("QLineEdit {\n"
                                        "    border: 3px solid rgb(245, 222, 179);\n"
                                        "    border-radius: 10px;\n"
                                        "    padding: 15px;\n"
                                        "    background-color:rgb(249, 234, 195);\n"
                                        "    color: rgb(45, 45, 45);\n"
                                        "}\n"
                                        "QLineEdit:hover {\n"
                                        "    border: 3px solid rgb(55, 55, 55);\n"
                                        "}\n"
                                        "QLineEdit:focus {\n"
                                        "    border: 3px solid rgb(135, 206, 250);\n"
                                        "    color: rgb(45, 45, 45);\n"
                                        "}")
        self.Senha_antiga.setText("")
        self.Senha_antiga.setAlignment(QtCore.Qt.AlignCenter)
        self.Senha_antiga.setObjectName("Senha_antiga")
        self.Senha_nova = QtWidgets.QLineEdit(Form)
        self.Senha_nova.setGeometry(QtCore.QRect(180, 150, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Senha_nova.setFont(font)
        self.Senha_nova.setStyleSheet("QLineEdit {\n"
                                      "    border: 3px solid rgb(245, 222, 179);\n"
                                      "    border-radius: 10px;\n"
                                      "    padding: 15px;\n"
                                      "    background-color:rgb(249, 234, 195);\n"
                                      "    color: rgb(45, 45, 45);\n"
                                      "}\n"
                                      "QLineEdit:hover {\n"
                                      "    border: 3px solid rgb(55, 55, 55);\n"
                                      "}\n"
                                      "QLineEdit:focus {\n"
                                      "    border: 3px solid rgb(135, 206, 250);\n"
                                      "    color: rgb(45, 45, 45);\n"
                                      "}")
        self.Senha_nova.setText("")
        self.Senha_nova.setAlignment(QtCore.Qt.AlignCenter)
        self.Senha_nova.setObjectName("Senha_nova")
        self.cria_conta = QtWidgets.QPushButton(Form, clicked = lambda: self.newUser())
        self.cria_conta.setGeometry(QtCore.QRect(450, 280, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.cria_conta.setFont(font)
        self.cria_conta.setStyleSheet("QPushButton{    \n"
                                      "    border: 3px solid rgb(245, 222, 179);\n"
                                      "    border-radius: 25px;\n"
                                      "    background-color:rgb(249, 234, 195);\n"
                                      "    color: rgb(45, 45, 45);\n"
                                      "}\n"
                                      "QPushButton:hover{    \n"
                                      "    border: 3px solid rgb(55, 55, 55);\n"
                                      "}\n"
                                      "QPushButton:pressed{    \n"
                                      "    background-color: rgb(135, 206, 250);\n"
                                      "    color: rgb(45, 45, 45);\n"
                                      "}")
        self.cria_conta.setObjectName("cria_conta")
        self.edita_senha = QtWidgets.QPushButton(Form, clicked = lambda: self.changePassword())
        self.edita_senha.setGeometry(QtCore.QRect(180, 220, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.edita_senha.setFont(font)
        self.edita_senha.setStyleSheet("QPushButton{    \n"
                                       "    border: 3px solid rgb(245, 222, 179);\n"
                                       "    border-radius: 25px;\n"
                                       "    background-color:rgb(249, 234, 195);\n"
                                       "    color: rgb(45, 45, 45);\n"
                                       "}\n"
                                       "QPushButton:hover{    \n"
                                       "    border: 3px solid rgb(55, 55, 55);\n"
                                       "}\n"
                                       "QPushButton:pressed{    \n"
                                       "    background-color: rgb(135, 206, 250);\n"
                                       "    color: rgb(45, 45, 45);\n"
                                       "}")
        self.edita_senha.setObjectName("edita_senha")
        self.frame_erro = QtWidgets.QFrame(Form)
        self.frame_erro.setGeometry(QtCore.QRect(170, 10, 450, 29))
        self.frame_erro.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_erro.setStyleSheet("background-color: rgb(255, 85, 127);\n"
                                      "border-radius: 10px;")
        self.frame_erro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_erro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_erro.setObjectName("frame_erro")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_erro)
        self.horizontalLayout_3.setContentsMargins(10, 3, 10, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_erro = QtWidgets.QLabel(self.frame_erro)
        self.label_erro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_erro.setObjectName("label_erro")
        self.horizontalLayout_3.addWidget(self.label_erro)
        self.pushButton_close = QtWidgets.QPushButton(self.frame_erro)
        self.pushButton_close.clicked.connect(lambda: self.hide_error())
        self.pushButton_close.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_close.setStyleSheet("QPushButton {\n"
                                            "    border-radius: 5px;    \n"
                                            "    background-image: url(:/Close_Image/Images/cil-x.png);\n"
                                            "    background-position: center;\n"
                                            "    background-color: rgb(255, 0, 127);\n"
                                            "}\n"
                                            "QPushButton:hover {\n"
                                            "    background-color: rgb(6, 21, 60);\n"
                                            "    color: rgb(200, 200, 200);\n"
                                            "}\n"
                                            "QPushButton:pressed {\n"
                                            "    background-color: rgb(35, 35, 35);\n"
                                            "    color: rgb(200, 200, 200);\n"
                                            "}")
        self.pushButton_close.setText("")
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_3.addWidget(self.pushButton_close)
        self.pushButton_close.setVisible(False)
        self.label_erro.setVisible(False)
        self.frame_erro.setVisible(False)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def changePassword(self):
        oldPwd = self.Senha_antiga.text()
        newPwd = self.Senha_nova.text()
        data = sqlite3.connect("inventory.db")
        cur = data.cursor()
        cur.execute("SELECT * FROM Login WHERE UserID = :id AND Password = :old", {'id': loginWindow.current,
                                                                                   'old': oldPwd})
        if not cur.fetchone():
            self.frame_erro.setStyleSheet("background-color: rgb(255, 85, 127);\n"
                                      "border-radius: 10px;")
            self.frame_erro.setVisible(True)
            self.label_erro.setVisible(True)
            self.pushButton_close.setVisible(True)
            self.label_erro.setText(QtCore.QCoreApplication.translate("Form", "Senha antiga errada"))
            data.commit()
            cur.close()
            data.close()
        else:
            cur.execute("UPDATE Login SET Password = :new WHERE UserID = :user", {'new': newPwd,
                                                                                  'user': loginWindow.current})
            self.Senha_antiga.clear()
            self.Senha_nova.clear()
            self.pushButton_close.setStyleSheet("QPushButton {\n"
                                                "    border-radius: 5px;    \n"
                                                "    background-image: url(:/Close_Image/Images/cil-x.png);\n"
                                                "    background-position: center;\n"
                                                "    background-color: rgb(0, 170, 0);\n"
                                                "}")
            self.frame_erro.setStyleSheet("background-color: rgb(85, 255, 127);\n"
                                          "border-radius: 10px;")
            self.frame_erro.setVisible(True)
            self.label_erro.setVisible(True)
            self.pushButton_close.setVisible(True)
            self.label_erro.setText(QtCore.QCoreApplication.translate("Form", "Senha alterada com sucesso"))
            data.commit()
            cur.close()
            data.close()

    def newUser(self):
        pwd = self.senha_user.text()
        user = self.Usuario.text()
        type = self.Tipo.text()
        if type.upper() != "A" and type.upper() != "U":
            self.frame_erro.setStyleSheet("background-color: rgb(255, 85, 127);\n"
                                          "border-radius: 10px;")
            self.pushButton_close.setStyleSheet("QPushButton {\n"
                                                "    border-radius: 5px;    \n"
                                                "    background-image: url(:/Close_Image/Images/cil-x.png);\n"
                                                "    background-position: center;\n"
                                                "    background-color: rgb(255, 0, 127);\n"
                                                "}\n"
                                                "QPushButton:hover {\n"
                                                "    background-color: rgb(6, 21, 60);\n"
                                                "    color: rgb(200, 200, 200);\n"
                                                "}\n"
                                                "QPushButton:pressed {\n"
                                                "    background-color: rgb(35, 35, 35);\n"
                                                "    color: rgb(200, 200, 200);\n"
                                                "}")
            self.frame_erro.setVisible(True)
            self.label_erro.setVisible(True)
            self.pushButton_close.setVisible(True)
            self.label_erro.setText(QtCore.QCoreApplication.translate("Form", "Tipo só pode ser A ou U"))
            self.senha_user.clear()
            self.Usuario.clear()
            self.Tipo.clear()
        else:
            data = sqlite3.connect("inventory.db")
            cur = data.cursor()
            try:
                cur.execute("INSERT INTO Login VALUES (:user, :pwd, :type)", {'user': user, 'pwd': pwd, 'type': type})
                self.frame_erro.setStyleSheet("background-color: rgb(85, 255, 127);\n"
                                              "border-radius: 10px;")
                self.pushButton_close.setStyleSheet("QPushButton {\n"
                                                    "    border-radius: 5px;    \n"
                                                    "    background-image: url(:/Close_Image/Images/cil-x.png);\n"
                                                    "    background-position: center;\n"
                                                    "    background-color: rgb(0, 170, 0);\n"
                                                    "}")
                self.frame_erro.setVisible(True)
                self.label_erro.setVisible(True)
                self.pushButton_close.setVisible(True)
                self.label_erro.setText(QtCore.QCoreApplication.translate("Form", "Usuário criado com sucesso"))
                self.senha_user.clear()
                self.Usuario.clear()
                self.Tipo.clear()
                data.commit()
                cur.close()
                data.close()
            except:
                self.frame_erro.setStyleSheet("background-color: rgb(255, 85, 127);\n"
                                              "border-radius: 10px;")
                self.pushButton_close.setStyleSheet("QPushButton {\n"
                                                    "    border-radius: 5px;    \n"
                                                    "    background-image: url(:/Close_Image/Images/cil-x.png);\n"
                                                    "    background-position: center;\n"
                                                    "    background-color: rgb(255, 0, 127);\n"
                                                    "}\n"
                                                    "QPushButton:hover {\n"
                                                    "    background-color: rgb(6, 21, 60);\n"
                                                    "    color: rgb(200, 200, 200);\n"
                                                    "}\n"
                                                    "QPushButton:pressed {\n"
                                                    "    background-color: rgb(35, 35, 35);\n"
                                                    "    color: rgb(200, 200, 200);\n"
                                                    "}")
                self.frame_erro.setVisible(True)
                self.label_erro.setVisible(True)
                self.pushButton_close.setVisible(True)
                self.label_erro.setText(QtCore.QCoreApplication.translate("Form", "Usuário já existente"))
                self.senha_user.clear()
                self.Usuario.clear()
                self.Tipo.clear()

    def hide_error(self):
        self.pushButton_close.setVisible(False)
        self.label_erro.setVisible(False)
        self.frame_erro.setVisible(False)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Usuario.setPlaceholderText(_translate("Form", "USUÁRIO"))
        self.senha_user.setPlaceholderText(_translate("Form", "SENHA"))
        self.Tipo.setPlaceholderText(_translate("Form", "TIPO DA CONTA"))
        self.Senha_antiga.setPlaceholderText(_translate("Form", "SENHA ANTIGA"))
        self.Senha_nova.setPlaceholderText(_translate("Form", "NOVA SENHA"))
        self.cria_conta.setText(_translate("Form", "CRIAR CONTA"))
        self.edita_senha.setText(_translate("Form", "EDITAR SENHA"))
        self.label_erro.setText(_translate("Form", "Error"))
