# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CONFIGURACOES.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(850, 440)
        Form.setMinimumSize(QtCore.QSize(850, 440))
        Form.setMaximumSize(QtCore.QSize(850, 440))
        self.Usuario = QtWidgets.QLineEdit(Form)
        self.Usuario.setGeometry(QtCore.QRect(450, 90, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Usuario.setFont(font)
        self.Usuario.setStyleSheet("QLineEdit {\n"
"    border: 3px solid rgb(245, 222, 179);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color:rgb(249, 234, 195);\n"
"    color: rgb(45, 45, 45);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(135, 206, 250);\n"
"    color: rgb(45, 45, 45);\n"
"}")
        self.Usuario.setText("")
        self.Usuario.setAlignment(QtCore.Qt.AlignCenter)
        self.Usuario.setObjectName("Usuario")
        self.senha_user = QtWidgets.QLineEdit(Form)
        self.senha_user.setGeometry(QtCore.QRect(450, 150, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.senha_user.setFont(font)
        self.senha_user.setStyleSheet("QLineEdit {\n"
"    border: 3px solid rgb(245, 222, 179);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color:rgb(249, 234, 195);\n"
"    color: rgb(45, 45, 45);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(135, 206, 250);\n"
"    color: rgb(45, 45, 45);\n"
"}")
        self.senha_user.setText("")
        self.senha_user.setAlignment(QtCore.Qt.AlignCenter)
        self.senha_user.setObjectName("senha_user")
        self.Tipo = QtWidgets.QLineEdit(Form)
        self.Tipo.setGeometry(QtCore.QRect(450, 210, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Tipo.setFont(font)
        self.Tipo.setStyleSheet("QLineEdit {\n"
"    border: 3px solid rgb(245, 222, 179);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color:rgb(249, 234, 195);\n"
"    color: rgb(45, 45, 45);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(135, 206, 250);\n"
"    color: rgb(45, 45, 45);\n"
"}")
        self.Tipo.setText("")
        self.Tipo.setAlignment(QtCore.Qt.AlignCenter)
        self.Tipo.setObjectName("Tipo")
        self.Senha_antiga = QtWidgets.QLineEdit(Form)
        self.Senha_antiga.setGeometry(QtCore.QRect(180, 90, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Senha_antiga.setFont(font)
        self.Senha_antiga.setStyleSheet("QLineEdit {\n"
"    border: 3px solid rgb(245, 222, 179);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color:rgb(249, 234, 195);\n"
"    color: rgb(45, 45, 45);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(135, 206, 250);\n"
"    color: rgb(45, 45, 45);\n"
"}")
        self.Senha_antiga.setText("")
        self.Senha_antiga.setAlignment(QtCore.Qt.AlignCenter)
        self.Senha_antiga.setObjectName("Senha_antiga")
        self.Senha_nova = QtWidgets.QLineEdit(Form)
        self.Senha_nova.setGeometry(QtCore.QRect(180, 150, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Senha_nova.setFont(font)
        self.Senha_nova.setStyleSheet("QLineEdit {\n"
"    border: 3px solid rgb(245, 222, 179);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color:rgb(249, 234, 195);\n"
"    color: rgb(45, 45, 45);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(135, 206, 250);\n"
"    color: rgb(45, 45, 45);\n"
"}")
        self.Senha_nova.setText("")
        self.Senha_nova.setAlignment(QtCore.Qt.AlignCenter)
        self.Senha_nova.setObjectName("Senha_nova")
        self.cria_conta = QtWidgets.QPushButton(Form)
        self.cria_conta.setGeometry(QtCore.QRect(450, 280, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.cria_conta.setFont(font)
        self.cria_conta.setStyleSheet("QPushButton{    \n"
"    border: 3px solid rgb(245, 222, 179);\n"
"    border-radius: 25px;\n"
"    background-color:rgb(249, 234, 195);\n"
"    color: rgb(45, 45, 45);\n"
"}\n"
"QPushButton:hover{    \n"
"    border: 3px solid rgb(55, 55, 55);\n"
"}\n"
"QPushButton:pressed{    \n"
"    background-color: rgb(135, 206, 250);\n"
"    color: rgb(45, 45, 45);\n"
"}")
        self.cria_conta.setObjectName("cria_conta")
        self.edita_senha = QtWidgets.QPushButton(Form)
        self.edita_senha.setGeometry(QtCore.QRect(180, 220, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.edita_senha.setFont(font)
        self.edita_senha.setStyleSheet("QPushButton{    \n"
"    border: 3px solid rgb(245, 222, 179);\n"
"    border-radius: 25px;\n"
"    background-color:rgb(249, 234, 195);\n"
"    color: rgb(45, 45, 45);\n"
"}\n"
"QPushButton:hover{    \n"
"    border: 3px solid rgb(55, 55, 55);\n"
"}\n"
"QPushButton:pressed{    \n"
"    background-color: rgb(135, 206, 250);\n"
"    color: rgb(45, 45, 45);\n"
"}")
        self.edita_senha.setObjectName("edita_senha")
        self.frame_erro = QtWidgets.QFrame(Form)
        self.frame_erro.setGeometry(QtCore.QRect(170, 10, 450, 29))
        self.frame_erro.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_erro.setStyleSheet("background-color: rgb(255, 85, 127);\n"
"border-radius: 10px;")
        self.frame_erro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_erro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_erro.setObjectName("frame_erro")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_erro)
        self.horizontalLayout_3.setContentsMargins(10, 3, 10, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_erro = QtWidgets.QLabel(self.frame_erro)
        self.label_erro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_erro.setObjectName("label_erro")
        self.horizontalLayout_3.addWidget(self.label_erro)
        self.pushButton_close = QtWidgets.QPushButton(self.frame_erro)
        self.pushButton_close.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_close.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;    \n"
"    background-image: url(:/Close_Image/Images/cil-x.png);\n"
"    background-position: center;\n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(6, 21, 60);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.pushButton_close.setText("")
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_3.addWidget(self.pushButton_close)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Usuario.setPlaceholderText(_translate("Form", "USUÁRIO"))
        self.senha_user.setPlaceholderText(_translate("Form", "SENHA"))
        self.Tipo.setPlaceholderText(_translate("Form", "TIPO DA CONTA"))
        self.Senha_antiga.setPlaceholderText(_translate("Form", "SENHA ANTIGA"))
        self.Senha_nova.setPlaceholderText(_translate("Form", "NOVA SNEHA"))
        self.cria_conta.setText(_translate("Form", "CRIAR CONTA"))
        self.edita_senha.setText(_translate("Form", "EDITAR SENHA"))
        self.label_erro.setText(_translate("Form", "Error"))
