# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CONFIGURACOES.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets

import loginWindow


class Ui_config(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(850, 440)
        Form.setMinimumSize(QtCore.QSize(850, 440))
        Form.setMaximumSize(QtCore.QSize(850, 440))
        self.edita_senha = QtWidgets.QPushButton(Form, clicked = lambda: self.changePassword())
        self.edita_senha.setGeometry(QtCore.QRect(130, 220, 131, 41))
        self.edita_senha.setObjectName("edita_senha")
        self.cria_conta = QtWidgets.QPushButton(Form, clicked = lambda: self.newUser())
        self.cria_conta.setGeometry(QtCore.QRect(390, 280, 141, 51))
        self.cria_conta.setObjectName("cria_conta")
        self.senha_user = QtWidgets.QLineEdit(Form)
        self.senha_user.setGeometry(QtCore.QRect(390, 150, 151, 51))
        self.senha_user.setObjectName("senha_user")
        self.Usuario = QtWidgets.QLineEdit(Form)
        self.Usuario.setGeometry(QtCore.QRect(390, 90, 151, 51))
        self.Usuario.setObjectName("Usuario")
        self.Senha_antiga = QtWidgets.QLineEdit(Form)
        self.Senha_antiga.setGeometry(QtCore.QRect(120, 90, 151, 51))
        self.Senha_antiga.setObjectName("Senha_antiga")
        self.Senha_nova = QtWidgets.QLineEdit(Form)
        self.Senha_nova.setGeometry(QtCore.QRect(120, 150, 151, 51))
        self.Senha_nova.setObjectName("Senha_nova")
        self.Tipo = QtWidgets.QLineEdit(Form)
        self.Tipo.setGeometry(QtCore.QRect(390, 210, 151, 51))
        self.Tipo.setObjectName("Tipo")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def changePassword(self):
        oldPwd = self.Senha_antiga.text()
        newPwd = self.Senha_nova.text()
        data = sqlite3.connect("inventory.db")
        cur = data.cursor()
        cur.execute("SELECT * FROM Login WHERE UserID = :id AND Password = :old", {'id': loginWindow.current,
                                                                                   'old': oldPwd})
        if not cur.fetchone():
            print("Senha errada")
            data.commit()
            cur.close()
            data.close()
        else:
            cur.execute("UPDATE Login SET Password = :new WHERE UserID = :user", {'new': newPwd,
                                                                                  'user': loginWindow.current})
            self.Senha_antiga.clear()
            self.Senha_nova.clear()
            data.commit()
            cur.close()
            data.close()

    def newUser(self):
        pwd = self.senha_user.text()
        user = self.Usuario.text()
        type = self.Tipo.text()
        data = sqlite3.connect("inventory.db")
        cur = data.cursor()
        cur.execute("INSERT INTO Login VALUES (:user, :pwd, :type)", {'user': user, 'pwd': pwd, 'type': type})
        self.senha_user.clear()
        self.Usuario.clear()
        self.Tipo.clear()
        data.commit()
        cur.close()
        data.close()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.edita_senha.setText(_translate("Form", "EDITAR SENHA"))
        self.cria_conta.setText(_translate("Form", "CRIAR NOVA CONTA"))
        self.senha_user.setText(_translate("Form", "SENHA"))
        self.Usuario.setText(_translate("Form", "NOME DE USUARIO"))
        self.Senha_antiga.setText(_translate("Form", "SENHA ANTIGA"))
        self.Senha_nova.setText(_translate("Form", "NOVA SENHA"))
        self.Tipo.setText(_translate("Form", "TIPO DA CONTA"))
