# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deletarproduto.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deleta(object):

    def deleta(self):
        data = sqlite3.connect("inventory.db")
        cur = data.cursor()
        codigo = self.lineEdit.text()

        if codigo:
            try:
                cur.execute("DELETE FROM Produtos WHERE Cod = :codigo", {'codigo': codigo})
                cur.execute("DELETE FROM Estoque WHERE Cod_prod = :codigo", {'codigo': codigo})
                cur.execute("DELETE FROM Movimentacao WHERE Cod_prod = :codigo", {'codigo': codigo})
                data.commit()
            except:
                print("Codigo invalido")
        else:
            print("Codigo invalido")
        cur.close()
        data.close()
        self.loadData()

    def loadData(self):
        data = sqlite3.connect("inventory.db")
        cur = data.cursor()

        cur.execute("SELECT * FROM Produtos")
        query = cur.fetchall()
        cur.execute("SELECT COUNT() FROM Produtos")

        count = cur.fetchone()
        self.tableWidget.setRowCount(count[0])

        tableIndex = 0
        for row in query:
            cur.execute("SELECT * FROM Categoria WHERE Cod = :codigo", {'codigo': row[1]})
            categoria = cur.fetchone()
            self.tableWidget.setItem(tableIndex, 0, QtWidgets.QTableWidgetItem(str(row[0])))
            self.tableWidget.setItem(tableIndex, 1, QtWidgets.QTableWidgetItem(row[2]))
            self.tableWidget.setItem(tableIndex, 2, QtWidgets.QTableWidgetItem(categoria[1]))
            self.tableWidget.setItem(tableIndex, 3, QtWidgets.QTableWidgetItem(str(row[5])))
            self.tableWidget.setItem(tableIndex, 4, QtWidgets.QTableWidgetItem(str(row[4])))
            self.tableWidget.setItem(tableIndex, 5, QtWidgets.QTableWidgetItem(row[3]))
            tableIndex += 1
        data.close()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(850, 400)
        Form.setMinimumSize(QtCore.QSize(850, 400))
        Form.setMaximumSize(QtCore.QSize(850, 400))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 10, 621, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color:rgb(249, 234, 195);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(600, 270, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{    \n"
                                      "    border: 3px solid rgb(245, 222, 179);\n"
                                      "    border-radius: 25px;\n"
                                      "    background-color:rgb(249, 234, 195);\n"
                                      "    color: rgb(45, 45, 45);\n"
                                      "}\n"
                                      "QPushButton:hover{    \n"
                                      "    border: 3px solid rgb(55, 55, 55);\n"
                                      "}\n"
                                      "QPushButton:pressed{    \n"
                                      "    background-color: rgb(135, 206, 250);\n"
                                      "    color: rgb(45, 45, 45);\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(100, 61, 641, 201))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget.setFont(font)
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
                                       "    border: 3px solid rgb(245, 222, 179);\n"
                                       "    border-radius: 10px;\n"
                                       "    padding: 15px;\n"
                                       "    background-color:rgb(249, 234, 195);\n"
                                       "    color: rgb(45, 45, 45);\n"
                                       "}")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(100, 270, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
                                    "    border: 3px solid rgb(245, 222, 179);\n"
                                    "    border-radius: 10px;\n"
                                    "    padding: 15px;\n"
                                    "    background-color:rgb(249, 234, 195);\n"
                                    "    color: rgb(45, 45, 45);\n"
                                    "}\n"
                                    "QLineEdit:hover {\n"
                                    "    border: 3px solid rgb(55, 55, 55);\n"
                                    "}\n"
                                    "QLineEdit:focus {\n"
                                    "    border: 3px solid rgb(135, 206, 250);\n"
                                    "    color: rgb(45, 45, 45);\n"
                                    "}")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")

        self.count = 0
        self.loadData()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "DELETAR PRODUTO"))
        self.pushButton.setText(_translate("Form", "DELETAR"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Cod. Prod"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Categoria"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Valor"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Custo"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Fornecedor"))
        self.lineEdit.setPlaceholderText(_translate("Form", "CÓDIGO DO PRODUTO"))
