# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deletarproduto.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deleta(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(850, 400)
        Form.setMinimumSize(QtCore.QSize(850, 400))
        Form.setMaximumSize(QtCore.QSize(850, 400))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(360, 20, 161, 41))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(50, 260, 161, 41))
        self.lineEdit.setAutoFillBackground(True)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(350, 340, 131, 41))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(50, 60, 611, 192))
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "DELETAR PRODUTO"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Código Produto"))
        self.pushButton.setText(_translate("Form", "DELETAR"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Cod. Prod"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Categoria"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Valor"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Custo"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Fabricante"))
