# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PROCURA.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(973, 545)
        Form.setStyleSheet("color:rgb(249, 234, 195);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 40, 701, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(249, 234, 195);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(100, 130, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 3px solid rgb(245, 222, 179);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color:rgb(249, 234, 195);\n"
"    color: rgb(45, 45, 45);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(135, 206, 250);\n"
"    color: rgb(45, 45, 45);\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(390, 130, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    border: 3px solid rgb(245, 222, 179);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color:rgb(249, 234, 195);\n"
"    color: rgb(45, 45, 45);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(135, 206, 250);\n"
"    color: rgb(45, 45, 45);\n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(320, 130, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(100, 200, 700, 300))
        self.tableWidget.setMinimumSize(QtCore.QSize(700, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(700, 300))
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    border: 3px solid rgb(245, 222, 179);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color:rgb(249, 234, 195);\n"
"    color: rgb(45, 45, 45);\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.Remove = QtWidgets.QPushButton(Form)
        self.Remove.setGeometry(QtCore.QRect(640, 130, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.Remove.setFont(font)
        self.Remove.setStyleSheet("QPushButton{    \n"
"    border: 3px solid rgb(245, 222, 179);\n"
"    border-radius: 25px;\n"
"    background-color:rgb(249, 234, 195);\n"
"    color: rgb(45, 45, 45);\n"
"}\n"
"QPushButton:hover{    \n"
"    border: 3px solid rgb(55, 55, 55);\n"
"}\n"
"QPushButton:pressed{    \n"
"    background-color: rgb(135, 206, 250);\n"
"    color: rgb(45, 45, 45);\n"
"}")
        self.Remove.setObjectName("Remove")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "PROCURAR PRODUTO"))
        self.lineEdit.setPlaceholderText(_translate("Form", "CÓDIGO DO PRODUTO"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "NOME DO PRODUTO"))
        self.label_2.setText(_translate("Form", "OU"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Cod. Mov"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Produto"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Cod. Prod"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Quantidade"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Tipo"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Data"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Fornecedor"))
        self.Remove.setText(_translate("Form", "PROCURAR"))
