# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VERIFICARESTOQUE.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_verificaEst(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(713, 524)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(230, 20, 231, 41))
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(40, 60, 600, 300))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setColumnWidth(0, 100)
        self.tableWidget.setColumnWidth(1, 250)
        self.tableWidget.setColumnWidth(2, 100)
        self.tableWidget.setColumnWidth(3, 100)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.retranslateUi(Form)
        self.loadData()
        QtCore.QMetaObject.connectSlotsByName(Form)

    def loadData(self):
        data = sqlite3.connect("inventory.db")
        cur = data.cursor()
        cur.execute("SELECT COUNT() FROM ESTOQUE")
        number = cur.fetchone()
        self.tableWidget.setRowCount(number[0])
        comando = "SELECT * FROM Estoque"
        tableIndex = 0
        for row in cur.execute(comando):
            cur.execute("SELECT * FROM Produtos WHERE Cod = :codigo",{'codigo': row[0]})
            produto = cur.fetchone()
            self.tableWidget.setItem(tableIndex, 0, QtWidgets.QTableWidgetItem(str(row[0])))
            self.tableWidget.setItem(tableIndex, 1, QtWidgets.QTableWidgetItem(str(produto[2])))
            self.tableWidget.setItem(tableIndex, 2, QtWidgets.QTableWidgetItem(str(row[1])))
            self.tableWidget.setItem(tableIndex, 3, QtWidgets.QTableWidgetItem(str(produto[1])))
            tableIndex += 1

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "VERIFICACAO DE ESTOQUE"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Cod Prod"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Produto"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Quantidade"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Categoria"))
